workflows:
  ios-workflow:
    name: iOS Release Build 801
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: binusman.application
      vars:
        APP_STORE_CONNECT_ISSUER_ID: "18e19531-f1a6-4489-93ec-016e4260b4fd"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "9F33Z6XYHY"
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
      xcode: latest
    scripts:
      - name: Set Build Number 801
        script: |
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion 801" "ios/App/App/Info.plist"
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString 1.0.0" "ios/App/App/Info.plist"

      - name: Build IPA with Fastlane
        script: |
          fastlane run build_app \
          project:"ios/App/App.xcodeproj" \
          scheme:"App" \
          export_method:"app-store" \
          output_directory:"build/ios/ipa" \
          output_name:"App.ipa"

      - name: Upload to TestFlight
        script: |
          fastlane run upload_to_testflight \
          ipa:"build/ios/ipa/App.ipa" \
          skip_waiting_for_build_processing:true
    artifacts:
      - build/ios/ipa/*.ipa
